version: '3.9'
services:
  builder:
    build: .
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true
    volumes:
      - ./output:/output
      # - ./ansible:/scripts/ansible
      # - ./build:/builddir

